### ISSUE TITLE
Create Expression<Func<T,bool>> from PrimaryKeyDictionary<T>

### ISSUE THREAD

**Issue by SergeyIlyin** [NickStrupat/EntityFramework.PrimaryKey#1]
Make function then return **Expression<Func<T,bool>>** (temp name:_MakeExpression_)
for use like this:
```
keyDic=???.
Expression<Func<T,bool>> func=keyDic.MakeExpression()
context.Set<T>().Include(t=>t.ComplexType).FirstOrDefault(keyDict.MakeExpression());
```
or with new Extention Find to IIncludableQueryable
```
context.Set<T>().Include(t=>t.ComplexType).Find(keyDic);
public static TEntity Find<TEntity, T>(this IIncludableQueryable<TEntity, T> includableQueryable, PrimaryKeyDictionary<TEntity> keys  ) where TEntity :class
    {
            includableQueryable.FirstOrDefault(keys.MakeExpression());
    }
```

**Comment by NickStrupat** [comment]
So you are interested in a `Find` overload which will use a primary key dictionary given by this library?

That is interesting...

EF gets us most of the way there already with this `Find` overload https://stackoverflow.com/a/23315582
Note that the keys have to be in order of their mapped column indices. So you can't just pass `primaryKeyDict.Values`.

I could probably override `Values` to return an ordered set, or maybe we could take a peak at what `Find(params Object[] keys)` is doing inside.

Also, I noticed your AutoHistory project. Have you seen my https://github.com/NickStrupat/EntityFramework.VersionedProperties ?

**Comment by SergeyIlyin** [comment]
The AutoHistory is not my project.

**Comment by SergeyIlyin** [comment]
https://github.com/NickStrupat/EntityFramework.PrimaryKey/pull/2
I think  that a good way to make ordered values.

BuildLambda will help to build query  for **IIncludableQueryable** . There are no any Find extention. But has FirstOrDefault
